### PR TITLE
Models

### PR DESCRIPTION
**Pull request by macjones743**
All of the new CAD drawings. I haven't changed any code or anything. Check it out and I'll be happy to fix any problems. Check out the CAD wiki section for renderings as well as a description of the build process and current concerns.

### CODE REVIEW

**Comment by Alexanderallenbrown** [comment]
Nice. One thing-- I don't see the new CAD wiki page. Any thoughts on why this might be?

**Comment by macjones743** [comment]
Just wrote in the mechanical design wiki section. Should I make a new wiki instead just for CAD?


Mac

----- Original Message -----

**Comment by Alexanderallenbrown** [comment]
nope, mech design is fine. Just needed a few taps on the "refresh" button
for it to show up.

Alexander Brown, Ph.D.
Assistant Professor
Department of Mechanical Engineering
Lafayette College
(610) 330-5417

**Comment by macjones743** [comment]
Looks pretty nifty, eh?

----- Original Message -----

**Comment by Alexanderallenbrown** [comment]
it is fantastic.

Alexander Brown, Ph.D.
Assistant Professor
Department of Mechanical Engineering
Lafayette College
(610) 330-5417

**Pull request merged**
